// SOCKET RELATED

export const SOCKET_NAMESPACES = {
  WALLET: '/wallet',
  ACCOUNT_CAPTURE: '/accountCapture'
}

export const SOCKET_EMITTERS = {
  USER_WALLET_BALANCE: 'USER_WALLET_BALANCE',
  ACCOUNT_CAPTURE: 'ACCOUNT_CAPTURE',
  USER_TRANSACTION: 'USER_TRANSACTION_STATUS'
}

export const SOCKET_LISTENERS = {
  USER_WALLET_BALANCE: SOCKET_NAMESPACES.WALLET + '/balance'

}

export const SOCKET_ROOMS = {
  USER_WALLET: 'USER_WALLET',
  ACCOUNT_CAPTURE: 'ACCOUNT_CAPTURE'
}
// SOCKET RELATED
