export const SUCCESS_MSG = {
  CREATE_SUCCESS: 'Record created successfully',
  CREATE_ERROR: 'Daily bonus already exists',
  GET_SUCCESS: 'Record get successfully',
  DELETE_SUCCESS: 'Record deleted successfully',
  USER_lOGOUT: 'User forcefully logout successfully',
  USER_TICKETS: 'User Ticket List',
  USER_TICKET_RESOLVED: 'User Ticket Resolved Successfully',
  USER_TICKET_ASSIGNED: 'User Ticket Assigned Successfully',
  UPDATE_SUCCESS: 'Record updated successfully',
  STATUS_UPDATED: 'Status has been updated successfully',
  VERIFICATION_EMAIL: 'Verification email is valid for ' + process.env.EMAIL_TOKEN_EXPIRY,
  DEPOSIT_SUCCESS: 'Amount added successfully',
  WITHDRAW_SUCCESS: 'Amount deducted successfully',
  EMAIL_SUCCESS: 'Email sent.',
  BONUS_ISSUE: 'Bonus issued successfully',
  CANCEL_SUCCESS: 'Bonus cancelled successfully',
  TRANSACTION_SUCCESS: 'Transaction status updated successfully.',
  REDIS_SUCCESS: 'PONG',
  HEALTHCHECK_SUCCESS: 'OK',
  METHOD: 'Healthcheck',
  UNLOCK_PLAYER_SUCCESS: 'Player Unlocked successfully',
  GENERATE_2FA_SUCCESS: 'Totp generated successfully',
  VERIFY_2FA_SUCCESS: 'Totp verified successfully',
  AUTH_DISABLE: '2FA updated successfully',
  SELF_EXCLUSION_DONE: 'Self exclusion done successfully'
}
